### ISSUE TITLE
pick not working under tmux

### ISSUE THREAD

**Issue by radostyle** [thoughtbot/pick#157]
I'm running on OSX. 

$ ls | pick
Traceback (most recent call last):
  File "/usr/local/Cellar/pick/0.0.2/libexec/src/pick.py", line 76, in <modul
    exit(main())
  File "/usr/local/Cellar/pick/0.0.2/libexec/src/pick.py", line 67, in main
    output = curses.wrapper(view.run)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.
urses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/Cellar/pick/0.0.2/libexec/src/view.py", line 58, in run
    self._setup_curses(screen)
  File "/usr/local/Cellar/pick/0.0.2/libexec/src/view.py", line 43, in _setup
rses
    curses.init_pair(1, 251, curses.COLOR_BLACK)
_curses.error: init_pair() returned ERR
$

**Comment by mptre** [comment]
I'm confused, this seems related to bernardorufino/pick and not
thoughtbot/pick. Looks like someone reported the same problem:
bernardorufino/pick#15.

**Comment by radostyle** [comment]
Sorry, I think you're right.
